# Generated by Django 6.0.6 on 2026-06-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_bodega_carrera_categoriaactivo_categoriainsumo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoActivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ASIGNACION", "Asignación"),
                            ("DEVOLUCION", "Devolución"),
                            ("TRASLADO", "Traslado"),
                            ("BAJA", "Baja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "ubicacion_anterior",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "ubicacion_nueva",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "activo_fijo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.activofijo",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario.persona",
                    ),
                ),
            ],
            options={
                "db_table": "movimientos_activos",
            },
        ),
    ]
